
language: go

sudo: false

go:
  - "1.11"
  - "1.12"
  - tip

before_install:
  - go get golang.org/x/sync/errgroup
  - go get github.com/pborman/uuid

script:
  - go test ./bql/... ./io/... ./storage/... ./tools/... ./triple/...
